#!/bin/sh
set -eu

# Generate Supabase credentials for the build from Xcode Cloud env vars.
#
# Required env vars (set in App Store Connect → Xcode Cloud → Workflow → Environment):
#   SUPABASE_URL       e.g. https://<project-ref>.supabase.co
#   SUPABASE_ANON_KEY  Supabase anon (public) key
#
# We bake the values into a Swift constants file because Xcode's
# `INFOPLIST_KEY_<custom>` mechanism does not reliably surface non-Apple
# keys to the bundled Info.plist (especially with the new
# PBXFileSystemSynchronizedRootGroup project format used here). The
# Swift file lives inside the synchronized SplitMate/ folder so it is
# automatically compiled into the target with no pbxproj edits.

if [ -z "${CI_PRIMARY_REPOSITORY_PATH:-}" ]; then
  echo "❌ CI_PRIMARY_REPOSITORY_PATH is not set. This script must run in Xcode Cloud."
  exit 1
fi

if [ -z "${SUPABASE_URL:-}" ] || [ -z "${SUPABASE_ANON_KEY:-}" ]; then
  echo "❌ Missing required env vars."
  echo "   SUPABASE_URL is $([ -n "${SUPABASE_URL:-}" ] && echo 'set' || echo 'EMPTY')"
  echo "   SUPABASE_ANON_KEY is $([ -n "${SUPABASE_ANON_KEY:-}" ] && echo 'set' || echo 'EMPTY')"
  echo "   Add them in App Store Connect → Xcode Cloud → Workflow → Environment."
  exit 1
fi

REPO="$CI_PRIMARY_REPOSITORY_PATH"
SWIFT_FILE="$REPO/SplitMate/Core/SupabaseBakedSecrets.swift"
XCCONFIG_DIR="$REPO/SplitMate/Config"
XCCONFIG_FILE="$XCCONFIG_DIR/Secrets.local.xcconfig"

mkdir -p "$(dirname "$SWIFT_FILE")"
mkdir -p "$XCCONFIG_DIR"

# 1) Bake values into the Swift constants file (primary path used by the app).
#    `\`-escape any `\` and `"` so the resulting Swift string literal stays valid.
escape_for_swift() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

ESCAPED_URL_SWIFT=$(escape_for_swift "$SUPABASE_URL")
ESCAPED_KEY_SWIFT=$(escape_for_swift "$SUPABASE_ANON_KEY")

cat > "$SWIFT_FILE" <<EOF
import Foundation

// AUTOGENERATED by ci_scripts/ci_post_clone.sh during the Xcode Cloud build.
// Do not edit by hand and do not commit real values.
enum SupabaseBakedSecrets {
    static let url: String = "$ESCAPED_URL_SWIFT"
    static let anonKey: String = "$ESCAPED_KEY_SWIFT"
}
EOF

# 2) Also write the xcconfig (kept for the local Release path / Info.plist
#    fallback). xcconfig treats `//` as a comment, so escape it via the
#    SLASH variable defined in Common.xcconfig (SLASH = /).
ESCAPED_URL_XCCONFIG=$(printf '%s' "$SUPABASE_URL" | sed 's|//|$(SLASH)$(SLASH)|g')

cat > "$XCCONFIG_FILE" <<EOF
SUPABASE_URL = $ESCAPED_URL_XCCONFIG
SUPABASE_ANON_KEY = $SUPABASE_ANON_KEY
EOF

KEY_LEN=${#SUPABASE_ANON_KEY}
echo "✅ Baked Supabase credentials into the build."
echo "   Wrote $SWIFT_FILE"
echo "   Wrote $XCCONFIG_FILE"
echo "   SUPABASE_URL       = $SUPABASE_URL"
echo "   SUPABASE_ANON_KEY  = (set, $KEY_LEN chars)"
